name: Deploy Web Server to AWS
on: 
  push: 
   branches: 
   - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Install AWS CLI Tool
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          echo aws --version
      - name: Configure AWS account
          #TODO

      - name: Run AWS Instance via CLI
          run: |
            aws ec2 run-instances --image-id ami-0f9fc25dd2506cf6d --count 1 --instance-type t2.micro --key-name {key_name} --security-group-ids {security_group} --user-data file://aws-up-file.sh



# aws ec2 terminate-instances --instance-ids {instance_id}


