name: Run Flask Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Flask Server
        run: |
          touch .env
          echo "API_KEY = ab6c5f31aaa48f332b5ffc67168bf1b69b849442" >> .env
          python3 simple_app.py
      - name: Run tests with pytest
        run: pytest 

