name: Deploy Web Server to AWS
on: 
  push: 
   branches: 
   - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2.5.8
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        env: 
          AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
        with:
          aws-access-key-id: $AWS_ACCESS_KEY
          aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
          aws-region: us-east-1
          
      - name: Checkout current repository
        uses: actions/checkout@v3
      - name: Run AWS Instance via CLI
        run: |
           aws ec2 run-instances --image-id ami-0f9fc25dd2506cf6d --count 1 --instance-type t2.micro --key-name Jack-Wagner-AWS-Key --security-group-ids sg-038003f5fea8708bc --user-data file://${{github.workspace}}/aws-up-file.sh



# aws ec2 terminate-instances --instance-ids {instance_id}


