name: Deploy Web Server to AWS
on: 
  push: 
   branches: 
   - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install AWS CLI
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2.5.8
          
      - name: Checkout current repository
        uses: actions/checkout@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
        
      - name: Terminate any open instances
        run: |
           source ${{github.workspace}}/terminate-current-instances.sh
        
        
      - name: Run AWS Instance via CLI
        run: |
           aws ec2 run-instances --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=btc-ticker}]' --image-id ami-0f9fc25dd2506cf6d --count 1 --instance-type t2.micro --key-name ${{ secrets.KEY_NAME }} --security-group-ids ${{ secrets.SECURITY_GROUP }} --user-data file://${{github.workspace}}/aws-up-file.sh > instance.txt
 
      - name: Output Instance Link
        run: |
          aws ec2 describe-instances --filters "Name=instance-type,Values=t2.micro"> instance.txt         
          INSTANCE_IP="$(grep -o '"PublicIpAddress": "[^"]*' instance.txt | grep -o '[^"]*$')"
          cat instance.txt
          echo "$INSTANCE_IP"
          echo "http://$INSTANCE_IP"
          
          


# aws ec2 terminate-instances --instance-ids {instance_id}


