name: Deploy Web Server to AWS
on: 
  push: 
   branches: 
   - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: 2.5.8
      - name: Configure AWS credentials from Production account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY_ID}}
          aws-region: us-east-1
          
      
      - name: Run AWS Instance via CLI
        run: |
           cp ${{github.workspace}}/aws-up-file.sh .
           chmod 600 aws-up-file.sh
           aws ec2 run-instances --image-id ami-0f9fc25dd2506cf6d --count 1 --instance-type t2.micro --key-name Jack-Wagner-AWS-Key --security-group-ids sg-038003f5fea8708bc --user-data file://aws-up-file.sh



# aws ec2 terminate-instances --instance-ids {instance_id}


